version: "3.3'
services:
          web:
                build:
                        context:
                        dockerfile: Dockerfile
                ports: 
                        - "8000:8000"
                volumes:
                          .:/app/
                env_file:
                          - ./. env
                environment:
                          - POSTGRES_HOST=postgres
                          - POSTGRES_DB=game
                          - POSTGRES_USER=postgres
                          - POSTGRES_PASSWORD=postgres
                depends_ on:
                          - db
                restart: always
                networks:
                          - practice
          db:
                image: "postgres"
                environment:
                          - POSTGRES_HOST=postgres
                          - POSTGRES_DB=game
                          - POSTGRES_USER=postgres
                          - POSTGRES_PASSWORD=postgres
                env_file:
                          - ./.env
                restart: always
                networks:
                          - practice
